def lint()
    use_frameworks!
    pod 'SwiftLint'
end

def eakit()
  use_frameworks!
  pod 'EAKit', :path => "../"
  lint()
end

target 'iOS' do
  platform :ios, '9.0'
  eakit()
end

target 'macOS' do
  platform :osx, '10.10'
  eakit()
end
